services:
  # PHP App Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sihafiz_app
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    environment:
      # Menggunakan IP Host (Laragon) agar database jadi satu
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=sihafiz_jatim
      - DB_USER=root
      - DB_PASS=
      - APP_URL=http://localhost:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sihafiz_network

networks:
  sihafiz_network:
    driver: bridge

